### ISSUE TITLE
Package wont install because arch

### ISSUE THREAD

**Issue by realopty** [adde88/hcxtools-hcxdumptool-openwrt#1]
```
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for hcxtools found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package hcxtools.
```

I've attempted to install your precompiled ipks but they fail on my ar71xx device

**Comment by adde88** [comment]
Could you please be more specific about your device?
What version of OpenWRT are you running, if it's not a WiFi Pineapple?
What kernel version are you running? uClibc, or musl?
