### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by realopty** [adde88/hcxtools-hcxdumptool-openwrt#2]
```
In file included from wlanhc2hcx.c:19:0:
common.h:191:2: error: #error Portability fix needed here
 #error Portability fix needed here
  ^~~~~
make[3]: *** [Makefile:81: wlanhc2hcx] Error 1
```

Make fails using openwrt buildroot because of said error on line 191 of common.h
Seems like auto-detection of endianness is non existant. How do you fix this with your builds?

**Comment by adde88** [comment]
I'll check into this. I'm compiling using the OpenWRT-SDK for 15.01 (CC), which you can get [here](http://archive.openwrt.org/chaos_calmer/15.05/ar71xx/generic/OpenWrt-SDK-15.05-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2):
