### ISSUE TITLE
cannot install on openwrt 18.6.2

### ISSUE THREAD

**Issue by bricco1981** [adde88/hcxtools-hcxdumptool-openwrt#3]
hi, can you helpme to install it on last stable openwrt 18.06.2 kernel 4.9.152,please? 
when i try to install the ipk i get this message:
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for hcxdumptool found, but incompatible with the architectures configured. it's musl. so the old version of mips24 work fine.

**Comment by cirolaferrara** [comment]
[Rebuild](https://openwrt.org/docs/guide-developer/quickstart-build-images) the image

**Comment by adde88** [comment]
You would need to compile it yourself with the Makefiles in this repo.
The IPK's are only compiled for Chaos Calmer (ar71xx), and sometimes for Snapshot, though rarely with musl support on the IPK's, as i enjoy the uClibc library a bit to much.
