### ISSUE TITLE
Update to latest release

### ISSUE THREAD

**Issue by sambul13** [adde88/hcxtools-hcxdumptool-openwrt#6]
Please update hcxdumptool for OpenWRT to V. 6.2.5 which has many new features. Pls also update hcxtools for OpenWRT. And pls push them to OpenWRT repo to install on any router model.

**Comment by adde88** [comment]
The latest release is often updated at my main package repo. first: https://github.com/adde88/openwrt-useful-tools
It's running v6.2.5.
This repo is simply missing the updates. I'll look into updating it. Until then, you can find it at my main repo. :)

**Comment by sambul13** [comment]
Hi Andreas,

Can you suggest how to disable wpa_supplicant before running hcxdumptool in
OpenWRT? See this
<https://forum.openwrt.org/t/running-tpl-wdr4900-radio-in-monitoring-mode/116893/3>
thread for details?

**Comment by adde88** [comment]
If ```wpa_supplicant``` is running on your OpenWRT installation, then i reckon it's also being used to connect as a STA to an AP.
Hence the need to run ```wpa_supplicant```.

And, whether to use ```wpa_supplicant```or not depends on your ```/etc/config/wireless``` setup.
If it's supposed to connect to an AP, with an adapter in STA mode, it will be mentioned within this config file.

You can also setup this config file to always launch an adapter in monitor mode.

If all your adapters are in monitor mode, ```wpa_supplicant``` would not be launched.

Also, if your device has several adapters, for example one (or more) adapters in monitor mode, and one running in STA mode, ```wpa_supplicant``` would be launched, and it would be using the adapter setup in the config file.
So, if you are running ```hcxdumptool``` on one adapter in monitor mode, and ```wpa_supplicant``` is using the other adapter in STA mode, then ```wpa_supplicant``` would not be able to interfere with ```hcxdumptool```.

I hope this made sense :)
